oz123/awesome-c

README.md
ISO conformant mini MP3 decoder with sse/neon support.
=> Add minimp3

README.md
=> Update adding fft-c package.

README.md
It seems that the website for reference 213 is no longer up and running (Internal server error when clicking on it).
I seem to have found another website that has a pdf version of it, so therefore I propose this file change.
=> A tutorial on pointers

README.md
A first-come first-served readers/writers lock.
=> Add FCFS RWLock.

README.md
[inih](https://github.com/benhoyt/inih) - A small and simple .INI file parser for C. [``BSD-3-Clause``][BSD-3-Clause]
=> Adding inih

README.md
I'm sorry but I had to fix empty spaces :)
=> Adding b63.

README.md
Cloudgizer project and link expired and deleted.
=> Cloudgizer project expired

README.md
ESBMC is a bounded model checker that helps to verifiy C code, it is a fork from CBMC using SMT Theories and addition of newer techniques to detemine the bound.
=> Addition of ESBMC

README.md
Hello, thank you very much with your project. I have added littlevGL in the list. Please double check the liscence to be sure I haven't made mistakes.
=> Add littlevGL graphical library

README.md
Add [ianh.owl](https://github.com/ianh/owl) - A parser generator for visibly pushdown languages.
=> Add ianh/owl

README.md
Adding [`str`](https://github.com/maxim2266/str) string library.
=> Adding "str" library.

README.md
I fell on this library when searching for a multi-platform system library.
I browse the code source, and built it over Windows.
As I developp now a lot on microprocessor, I'm not going to use it, but it would have help me a lot in the past, since was i was doing many ports projects.
Best Regards
=> add plibsys

README.md
=> Added astera for issue #173

README.md
Hi, 
This library contains many smaller libraries, I wasn't sure where to add but I've added under data structures, hope it's okay. 
Thanks.
=> add sc library

README.md
Tau is a Micro Unit testing framework built in C, for C. It includes a rich set of assertion macros, supports automatic test registration and can output to multiple formats, like the TAP format or JUnit XML. Supported on Linux, macOS, FreeBSD, and Windows.
=> Update README: Add the Tau testing Framework

README.md
The project branding changed about a year ago.
=> LittlevGL -> LVGL in README.md

README.md
I don't know why there wasn't link there, but I added it.
=> fixing incbin link and license

README.md
https://github.com/helderman/htpataic
=> Add "How to program a text adventure in C"

README.md
Concord is a Discord API wrapper library compatible with C99
=> Add Concord

README.md
=> Added exengine to Game Programming section

README.md
The post has no content anymore
=> remove I do not know C

README.md
=> add Build Your Own Text Editor

README.md
Hi,
Stjepan here from Manning. I thought this title might be a good match for your list. Thank you for considering it.
Best,
=> Added Modern C, Third Edition: Covers the C23 standard

README.md
The previous link for LMDB was dead
=> Update link for LMDB

README.md
Introduces a new database, designed for fast, in-process analytical tasks.
The database provides a C API for seamless integration into existing projects, offering users a powerful tool for efficient data analysis within applications.
=> Added new database: Fast in-process analytical database with C API.
