oz123/awesome-c

README.md

This is a single-file header file that contains singly-linked and doubly-linked implementations for linked list operations. I've used it fairly extensively as it saves a significant amount of time when doing coursework/projects that require linked lists.
The [README](https://github.com/nbulischeck/list.h/blob/master/README.md) is full of examples and decent documentation.

Added list.h

---

README.md

`libcsv` is now maintained at the linked GitHub repository; the information is provided by the author himself in the SF download page.

Updated libcsv link

---

README.md

Added my MQTT-C client to the Networking and Internet subsection.
MQTT-C is an MQTT v3.1.1 client written in C. MQTT is a lightweight publisher-subscriber-based messaging protocol that is commonly used in IoT and networking applications where high-latency and low data-rate links are expected. The purpose of MQTT-C is to provide a portable MQTT client, written in C, for embedded systems and PC's alike. MQTT-C does this by providing a transparent Platform Abstraction Layer (PAL) which makes porting to new platforms easy. MQTT-C is completely thread-safe but can also run perfectly fine on single-threaded systems making MQTT-C well-suited for embedded systems and microcontrollers. Finally, MQTT-C is small; there are only two source files totalling less than 2000 lines.
Cheers,
Liam

Added MQTT-C to "Networking and Internet"

---

README.md

The link of the igraph library was for the Cloudgizer library. Fixed it.

Fixed the igraph library link

---

README.md

greatest is not released under the MIT license.
https://github.com/silentbicycle/greatest/blob/master/LICENSE

Fix greatest license (MIT -> ISC)

---

README.md

Musl has changed from https://www.musl-libc.org/ to https://musl.libc.org/ .

Update musl link.

---

README.md

It's primarily a C library, since I don't write C++, but there is C++ compatibility left over from the original project that I didn't touch.
Let me know if you think it would fit better in [awesome-cpp](https://github.com/fffaraz/awesome-cpp).

Add Rogueutil, a header-only TUI library

---

README.md

EJDB2 is an embeddable JSON database engine published under MIT license.

Added EJDB2 JSON database engine

---

README.md

Hi,
Here a few good libraries to add the list.
I was working on 3D (maybe + 2D later) importer and util library written in pure 100% C. It is ready to be public. It can import glTF 2.0, COLLADA 1.4/1.41/1.5 files with single interface. Its size is very small e.g ~244KB + stb_image.h (160KB) == ~404KB. And it provides lot of options and utils to make loading and rendering stages flexible, fast as possible. In the future it may support additional formats to import and export.
To make AssetKit portable, make build fast and make parsing XML easy, I have dropped libxml2 and wrote new XML parser (and a JSON parser). I have used it in AssetKit to parse XMLs. 
The XML parser doesn't alloc and copy XML contents... It only allocs memory for data structure or tokens. It creates pointers by using …

add AssetKit, xml and cmt graphics library

---

README.md

- [**silgy**](https://github.com/silgy/silgy) - Asynchronous HTTP(S) engine for C/C++ projects. [``MIT``](https://spdx.org/licenses/MIT.html)
- [**obj.h**](https://github.com/small-c/obj.h) - A single-header supports OOP in pure C. [``MIT``](https://spdx.org/licenses/MIT.html)
<br>
```diff
...
+[578]: https://github.com/silgy/silgy
+[579]: https://github.com/small-c/obj.h
```

Add silgy, obj.h

---

README.md

http://liblfds.org/
> All sites on this server are https only.

liblfds: http->https

---

README.md

This patchset does two things in the networking section:
* Fixes the ordering of `libpcap`
* Adds core `libzmq` (C API, C++ backend) to the list

net: add libzmq, fix ordering

---

README.md

This commit adds `libnl` Netlink library to the networking section,
and points the link to the offical page of `libnl` (github repository
links on that page).
**Note**: this PR builds on top of #160

net: add libnl (Netlink)

---

README.md

This patcheset (2), adds:
* Autotools: the GNU build system (`automake`, `autoconf`, `libtool`). There is no specific page for it, so the introduction to "the system" is as part of the `automake` manual.
* msune/autotools-skeleton: a template for bootstrapping autotools projects.
**NOTE**: this PR builds on top of #161 and #160, respectively, for the sake of avoiding unnecessary rebases (specially with refs). If necessary, I can rebased them on top of current `HEAD` of master to be integrated before the others

build: autotools and autotools-skeleton

---

README.md

This patchset:
* Reorders Alphabetically `Data Structures` section
* Adds entry in this section for `libcdada`, a small MACRO-less library for basic data structures (`list`, `set`, `map`...) in C (C++ backend). 
**NOTE**: for easy integration this PR builds on top of #162, #161, #160

data-structures: order section and add libcdada

---

README.md

Add two websites for learning C programming:
- CodeforWin: is a good website for learning C programming, data structures tutorials, exercises, tips and tricks online. So, I added this website in C programming learning, reference, tutorials section as beginner resources online.
- Learn-C.org: is a free and open-source website for learning C programming
online for beginners. It also provides programming playground-style online code
editor for exercises and directly run C code on their website.

Update README: Add learning resources in C reference section

---

README.md

`json-c` is not a single-file or single-header. It is a complete library which requires building and linking.

fix typo "json.c" -> "json-c"

---

README.md

`m2cgen` is a lightweight library with command line interface which allows to transpile trained machine learning models into a native code of C programming language. Examples of generated C code can be found [here](https://github.com/BayesWitnesses/m2cgen/tree/master/generated_code_examples/c).

Adding m2cgen for transpiling ML models into C code

---

README.md

Upstream developers recommend to switch to their own fork.

Replace http-parser with llhttp

---

README.md

This is a various licenses, according [here](https://github.com/pspdev/pspsdk#introduction). this is what it says:
> PSPSDK is distributed under a BSD-compatible license, with the exception of the files located in tools/PrxEncrypter. The files located in the tools/PrxEncrypter directory are subject to the terms of the GNU General Public License version 3. See the LICENSE files for more information.

add pspsdk

---

README.md

This link leads to a log-in with no option to register.

remove C Programming Language Certified Associate preparation course

---

README.md

The previous link directed to a website that appeared to be irrelevant to the in-memory database. This commit replaces it with a link to the WhiteDB source code repository, providing users with direct access to the relevant codebase.

Updated link to point to the source code repository of WhiteDB.

---

README.md

Adding NAppGUI 
NAppGUI is a professional SDK to build cross-platform desktop applications using The C Programming Language (ANSI C90). 
NAppGUI is built as a lightweight layer on top of the operating system native APIs, that allows create portable programs extremely fast and small without any external dependency.

Adding nappgui
